// ─── Starter Recipe Templates ─────────────────────────────────────────────────
// Seeded automatically on first Fuel tab visit when recipe repo is empty

import type { RecipeIngredient } from '@/types/database'

export interface StarterRecipe {
  name: string
  servings: number
  kcal_total: number
  protein_total: number
  carbs_total: number
  fat_total: number
  ingredients: RecipeIngredient[]
  notes: string
}

export const STARTER_RECIPES: StarterRecipe[] = [
  {
    name: 'Overnight Oats',
    servings: 1,
    kcal_total: 420,
    protein_total: 22,
    carbs_total: 58,
    fat_total: 10,
    ingredients: [
      { name: 'Rolled oats', quantity: 80, unit: 'g' },
      { name: 'Milk', quantity: 200, unit: 'ml' },
      { name: 'Greek yogurt', quantity: 100, unit: 'g' },
      { name: 'Banana', quantity: 1, unit: 'piece' },
      { name: 'Honey', quantity: 1, unit: 'tbsp' },
      { name: 'Chia seeds', quantity: 10, unit: 'g' },
    ],
    notes: 'Mix oats, milk and yogurt the night before. Top with banana and honey in the morning. Great pre-long-run breakfast.',
  },
  {
    name: 'Chicken & Rice (Recovery)',
    servings: 2,
    kcal_total: 740,
    protein_total: 72,
    carbs_total: 82,
    fat_total: 10,
    ingredients: [
      { name: 'Chicken breast', quantity: 400, unit: 'g' },
      { name: 'White rice', quantity: 160, unit: 'g' },
      { name: 'Broccoli', quantity: 200, unit: 'g' },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'Garlic', quantity: 2, unit: 'piece' },
      { name: 'Soy sauce', quantity: 1, unit: 'tbsp' },
    ],
    notes: 'Classic post-run recovery meal. High protein and simple carbs. Cook rice and steam broccoli while grilling chicken.',
  },
  {
    name: 'Pasta Bolognese',
    servings: 3,
    kcal_total: 1350,
    protein_total: 81,
    carbs_total: 180,
    fat_total: 27,
    ingredients: [
      { name: 'Pasta', quantity: 300, unit: 'g' },
      { name: 'Beef mince (lean)', quantity: 400, unit: 'g' },
      { name: 'Chopped tomatoes', quantity: 400, unit: 'g' },
      { name: 'Onion', quantity: 1, unit: 'piece' },
      { name: 'Garlic', quantity: 3, unit: 'piece' },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp' },
    ],
    notes: 'Pre long-run carb-load dinner. Make the night before a big session. Simple and effective.',
  },
  {
    name: 'Protein Smoothie',
    servings: 1,
    kcal_total: 380,
    protein_total: 38,
    carbs_total: 42,
    fat_total: 7,
    ingredients: [
      { name: 'Whey protein powder', quantity: 30, unit: 'g' },
      { name: 'Banana', quantity: 1, unit: 'piece' },
      { name: 'Milk', quantity: 300, unit: 'ml' },
      { name: 'Peanut butter', quantity: 1, unit: 'tbsp' },
      { name: 'Blueberries', quantity: 80, unit: 'g' },
    ],
    notes: 'Post-run recovery shake. Drink within 30 minutes of finishing. Blend until smooth.',
  },
  {
    name: 'Salmon & Sweet Potato',
    servings: 2,
    kcal_total: 820,
    protein_total: 64,
    carbs_total: 72,
    fat_total: 28,
    ingredients: [
      { name: 'Salmon fillet', quantity: 400, unit: 'g' },
      { name: 'Sweet potato', quantity: 400, unit: 'g' },
      { name: 'Spinach', quantity: 100, unit: 'g' },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon', quantity: 1, unit: 'piece' },
    ],
    notes: 'Omega-3 rich recovery dinner. Bake salmon and sweet potato together at 200°C for 25 minutes.',
  },
  {
    name: 'Banana & Peanut Butter Toast',
    servings: 1,
    kcal_total: 320,
    protein_total: 12,
    carbs_total: 48,
    fat_total: 10,
    ingredients: [
      { name: 'Sourdough bread', quantity: 2, unit: 'slice' },
      { name: 'Peanut butter', quantity: 2, unit: 'tbsp' },
      { name: 'Banana', quantity: 1, unit: 'piece' },
    ],
    notes: 'Quick pre-run snack (90 mins before). Easy to digest, good energy for an easy or medium session.',
  },
  {
    name: 'Greek Yogurt Bowl',
    servings: 1,
    kcal_total: 310,
    protein_total: 28,
    carbs_total: 38,
    fat_total: 5,
    ingredients: [
      { name: 'Greek yogurt (0% fat)', quantity: 250, unit: 'g' },
      { name: 'Granola', quantity: 40, unit: 'g' },
      { name: 'Mixed berries', quantity: 100, unit: 'g' },
      { name: 'Honey', quantity: 1, unit: 'tsp' },
    ],
    notes: 'High-protein snack or light breakfast. Good on rest days when calorie targets are lower.',
  },
  {
    name: 'Homemade Energy Gel',
    servings: 4,
    kcal_total: 400,
    protein_total: 0,
    carbs_total: 100,
    fat_total: 0,
    ingredients: [
      { name: 'Maltodextrin', quantity: 60, unit: 'g' },
      { name: 'Fructose', quantity: 30, unit: 'g' },
      { name: 'Water', quantity: 120, unit: 'ml' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
    ],
    notes: '2:1 maltodextrin:fructose ratio. Each portion = 25g carbs. Take every 45min on long runs. Add caffeine powder for race day version.',
  },
  // PR F2 — expanded set covering breakfast / pre-run / lunch / post-run /
  // dinner / snack with broader macro variety. Founder owns long-term
  // recipe content; this gets the library feeling populated for new users.
  {
    name: 'Eggs on Toast',
    servings: 1,
    kcal_total: 380,
    protein_total: 24,
    carbs_total: 32,
    fat_total: 18,
    ingredients: [
      { name: 'Eggs', quantity: 3, unit: 'piece' },
      { name: 'Sourdough bread', quantity: 2, unit: 'slice' },
      { name: 'Butter', quantity: 1, unit: 'tsp' },
      { name: 'Avocado', quantity: 0.5, unit: 'piece' },
    ],
    notes: 'Default breakfast on rest days or before easy sessions. Scramble or poach eggs; mash avocado on toast.',
  },
  {
    name: 'Porridge with Berries',
    servings: 1,
    kcal_total: 360,
    protein_total: 14,
    carbs_total: 60,
    fat_total: 7,
    ingredients: [
      { name: 'Rolled oats', quantity: 60, unit: 'g' },
      { name: 'Milk', quantity: 250, unit: 'ml' },
      { name: 'Mixed berries', quantity: 80, unit: 'g' },
      { name: 'Honey', quantity: 1, unit: 'tsp' },
    ],
    notes: 'Warm breakfast for cold mornings. Cook oats in milk, stir in berries off the heat. 1-2h before steady or tempo.',
  },
  {
    name: 'Tuna Pasta Salad',
    servings: 1,
    kcal_total: 540,
    protein_total: 38,
    carbs_total: 62,
    fat_total: 14,
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Tuna (tinned)', quantity: 1, unit: 'piece' },
      { name: 'Cherry tomatoes', quantity: 100, unit: 'g' },
      { name: 'Sweetcorn', quantity: 80, unit: 'g' },
      { name: 'Olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'Lemon', quantity: 0.5, unit: 'piece' },
    ],
    notes: 'Lunch when you need fuel for a hard session later. Cook pasta, cool, fold in tuna + veg + dressing.',
  },
  {
    name: 'Halloumi Wrap',
    servings: 1,
    kcal_total: 580,
    protein_total: 30,
    carbs_total: 52,
    fat_total: 26,
    ingredients: [
      { name: 'Halloumi', quantity: 100, unit: 'g' },
      { name: 'Tortilla wrap', quantity: 1, unit: 'piece' },
      { name: 'Hummus', quantity: 2, unit: 'tbsp' },
      { name: 'Spinach', quantity: 30, unit: 'g' },
      { name: 'Roasted red peppers', quantity: 50, unit: 'g' },
    ],
    notes: 'Vegetarian lunch. Pan-fry halloumi until golden; build wrap. Filling and satisfying without being heavy.',
  },
  {
    name: 'Beef Stir-Fry',
    servings: 1,
    kcal_total: 520,
    protein_total: 42,
    carbs_total: 50,
    fat_total: 14,
    ingredients: [
      { name: 'Beef strips (lean)', quantity: 150, unit: 'g' },
      { name: 'Egg noodles', quantity: 80, unit: 'g' },
      { name: 'Mixed stir-fry veg', quantity: 200, unit: 'g' },
      { name: 'Soy sauce', quantity: 1, unit: 'tbsp' },
      { name: 'Sesame oil', quantity: 1, unit: 'tsp' },
      { name: 'Ginger', quantity: 1, unit: 'tsp' },
    ],
    notes: 'Fast post-run dinner. 15min total. High iron, restores glycogen, easy on the stomach.',
  },
  {
    name: 'Chickpea Curry',
    servings: 2,
    kcal_total: 700,
    protein_total: 30,
    carbs_total: 96,
    fat_total: 18,
    ingredients: [
      { name: 'Chickpeas (tinned)', quantity: 2, unit: 'piece' },
      { name: 'Basmati rice', quantity: 160, unit: 'g' },
      { name: 'Chopped tomatoes', quantity: 400, unit: 'g' },
      { name: 'Coconut milk', quantity: 200, unit: 'ml' },
      { name: 'Onion', quantity: 1, unit: 'piece' },
      { name: 'Curry powder', quantity: 2, unit: 'tbsp' },
    ],
    notes: 'Plant-based dinner. Make a double batch — reheats well for the next day. Good before long runs.',
  },
  {
    name: 'Bagel with Cream Cheese',
    servings: 1,
    kcal_total: 380,
    protein_total: 14,
    carbs_total: 56,
    fat_total: 12,
    ingredients: [
      { name: 'Plain bagel', quantity: 1, unit: 'piece' },
      { name: 'Cream cheese', quantity: 30, unit: 'g' },
      { name: 'Smoked salmon', quantity: 40, unit: 'g' },
    ],
    notes: 'Race-morning standby. Easy to digest, sits well in nervous stomach, plenty of carbs. 2-3h before start.',
  },
  {
    name: 'Apple & Almond Butter',
    servings: 1,
    kcal_total: 240,
    protein_total: 6,
    carbs_total: 28,
    fat_total: 14,
    ingredients: [
      { name: 'Apple', quantity: 1, unit: 'piece' },
      { name: 'Almond butter', quantity: 1, unit: 'tbsp' },
    ],
    notes: 'Snack between meals. Or 60-90min before easy/recovery sessions when you want something light.',
  },
  {
    name: 'Cottage Cheese & Pineapple',
    servings: 1,
    kcal_total: 200,
    protein_total: 24,
    carbs_total: 20,
    fat_total: 3,
    ingredients: [
      { name: 'Cottage cheese (low-fat)', quantity: 200, unit: 'g' },
      { name: 'Pineapple', quantity: 100, unit: 'g' },
    ],
    notes: 'Pre-bed protein hit. Casein in the cottage cheese feeds muscles overnight after a hard session.',
  },
  {
    name: 'Spaghetti Aglio e Olio',
    servings: 1,
    kcal_total: 560,
    protein_total: 14,
    carbs_total: 86,
    fat_total: 16,
    ingredients: [
      { name: 'Spaghetti', quantity: 100, unit: 'g' },
      { name: 'Garlic', quantity: 4, unit: 'piece' },
      { name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'Chilli flakes', quantity: 1, unit: 'tsp' },
      { name: 'Parmesan', quantity: 20, unit: 'g' },
    ],
    notes: 'Carb-load dinner the night before a long run or race. 10 minutes from pan to plate. Add chicken if you want more protein.',
  },
]
